### PR TITLE
Label the nodes for OCP-4.4

### PR DESCRIPTION
**Pull request by capolrik**
Fix regression introduced by the removal of labels role.

### CODE REVIEW

**Comment by capolrik** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Review by krsacme — APPROVED** [review]

**Comment by capolrik** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Comment by capolrik** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Comment by capolrik** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Comment by capolrik** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Comment by capolrik** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Pull request merged**
