### PR TITLE
Allow the reponame to be configurable to suport 4.6 index repo

### PR DESCRIPTION
**Pull request by krsacme**

### CODE REVIEW

**Comment by tvass** [comment]
check dallas ocp-4.5-vanilla example-cnf

**Comment by tvass** [comment]
check dallas ocp-4.5-vanilla example-cnf

**Comment by tvass** [comment]
check dallas ocp-4.5-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.5-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.5-vanilla example-cnf

**Pull request merged**
