### PR TITLE
Hooks refactor

### PR DESCRIPTION
**Pull request by tonyskapunk**
This change is related to the change 20681 in the dci-openshift-app-agent, it only moves some steps from install to pre-run, it should not depend on 20681 at this point.

Depends-on: 20840

### CODE REVIEW

**Comment by tonyskapunk** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Review by krsacme — APPROVED** [review]

**Comment by tonyskapunk** [comment]
Depends-on: 20840

**Comment by fredericlepied** [comment]
> Depends-on: 20840

it should be in the description of the PR. not in a comment. I have made the change in the description.

**Comment by flepied** [comment]
check dallas test

**Comment by fredericlepied** [comment]
check dallas test

**Comment by tonyskapunk** [comment]
check dallas ocp-4.4-vanilla example-cnf

**Review by p3ck — APPROVED** [review]

**Comment by tonyskapunk** [comment]
check dallas ocp-4.6-vanilla example-cnf

**Pull request merged**
