### PR TITLE
Remove explicit labels as affinity is used

### PR DESCRIPTION
**Pull request by krsacme**

### CODE REVIEW

**Comment by krsacme** [comment]
check dallas ocp-4.6-vanilla example-cnf

**Comment by krsacme** [comment]
check dallas ocp-4.6-vanilla example-cnf

**Comment by krsacme** [comment]
check dallas ocp-4.5-vanilla example-cnf

**Comment by krsacme** [comment]
> ocp-4.6-vanilla example-cnf FAILURE https://www.distributed-ci.io/jobs/3732b4e0-cebc-4150-93e3-b34e264fe779/jobStates https://www.distributed-ci.io/jobs/e9feb376-280e-4847-a6f8-4431ab9264c3/jobStates from #18

Images are not synced to internal registry. Added now.  Need to work on creating a mirror entry and automate image sync within example-cnf itself so that manual effort can be removed.

**Comment by krsacme** [comment]
> ocp-4.5-vanilla example-cnf SUCCESS https://www.distributed-ci.io/jobs/c4d0362b-a3cc-4ac4-98a8-e92ddb65a7f8/jobStates https://www.distributed-ci.io/jobs/0ac08d82-2a27-4569-8305-321843a02a4e/jobStates from #18

@fredericlepied ptal

Pods with anti-affinity are working fine, refer to the [log](https://www.distributed-ci.io/files/91a8530e-ec5f-4151-93f7-8d5fd52685d0) where LB and TestPMD pods are not in the same nodes. And LB and TRex Pods are not in the same nodes.

**Review by fredericlepied — APPROVED** [review]

**Pull request merged**
